//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.15 at 09:23:47 오후 KST 
//


package member;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import java.util.Iterator;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}header"/>
 *         &lt;element ref="{}body"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "body"
})
@XmlRootElement(name = "horseRace")
public class HorseRace implements Cloneable{

    @XmlElement(required = true)
    protected Header header;
    @XmlElement(required = true)
    protected Body body;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * @return
     *     possible object is
     *     {@link Body }
     *     
     */
    public Body getBody() {
        return body;
    }

    /**
     * Sets the value of the body property.
     * 
     * @param value
     *     allowed object is
     *     {@link Body }
     *     
     */
    public void setBody(Body value) {
        this.body = value;
    }
    
    public void setPlayer(List list){
    	this.getBody().getPlayers().setPlayer(list);
    }
    public List getPlayers(){
    	return body.getPlayers().getPlayer();
    }
    public Player getPlayer(int index){
    	return body.players.player.get(index);
    }
    
    public void setHorse(List list){
    	this.getBody().getHorses().setHorse(list);
    }
    public List getHorses(){
    	return body.getHorses().getHorse();
    }
    public Horse getHorse(int index){
    	return body.horses.horse.get(index);
    }
    
    public void setResult(List list){
    	this.getBody().getResults().setResult(list);
    }
    public List getResults(){
    	return body.getResults().getResult();
    }
    public Result getResult(int index){
    	return body.results.result.get(index);
    }
    /**
	 * HorseRace객체를 자식 요소와 함께 간편하게 생성할 수 있는 메서드.<br>
	 * HorseRace에 맞는 XML의 기본적 계층 구조가 모두 마련된다.
	 */
    public void createChilds(){
		this.setHeader(new Header());
		this.setBody(new Body());
		this.getBody().setPlayers(new Players());
		this.getBody().setHorses(new Horses());
		this.getBody().setResults(new Results());
    }
    
    public HorseRace clone(){
    	try {
			return (HorseRace)super.clone();
		} catch (CloneNotSupportedException e) {
			return null;
		}
    }
}
