//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.15 at 07:35:38 오후 KST 
//


package member;

import java.awt.Image;
import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}member">
 *       &lt;sequence>
 *         &lt;element name="nick" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{}horseType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nick",
    "type"
})
@XmlRootElement(name = "horse")
public class Horse
    extends Member implements IMember, Serializable
{

    @XmlElement(required = true)
    protected String nick;
    @XmlElement(required = true, defaultValue = "GermanHolstein")
    protected HorseType type;

    public Horse(){}
    public Horse(String id, String name, int age, boolean gender, double height, double weight, String picURL, String nick, HorseType type){
		super(id, name, age, gender, height, weight, picURL);
		this.nick = nick;
		this.type = type;
	}
    /**
     * Gets the value of the nick property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNick() {
        return nick;
    }

    /**
     * Sets the value of the nick property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNick(String value) {
        this.nick = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link HorseType }
     *     
     */
    public HorseType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link HorseType }
     *     
     */
    public void setType(HorseType value) {
        this.type = value;
    }

    public String[] toStrings(){
    	String[] tmp = super.toStrings();
    	String[] str = new String[tmp.length+2];
    	int i = 0;
    	for(String ts: tmp){
    		str[i++] = ts;
    	}
    	str[7] = this.nick;
    	str[8] = this.type.toString();
    	return str;
    }
    public Object[] toArray(){
    	Object[] tmp = super.toArray();
    	Object[] obj = new Object[tmp.length+2];
    	int i = 0;
    	for(Object to: tmp){
    		obj[i++] = to;
    	}
    	obj[7] = nick;
    	obj[8] = type;
    	return obj;
    }
	public String[] getColumnName(){
		String[] str = {"말 식별 번호", "이름", "나이", "성별", "신장(m)", "몸무게(kg)", "사진", "별명", "말 종류"};
		return str;
    }
	public void setData(String... str){
		super.setData(str[0], str[1], str[2], str[3], str[4], str[5], str[6]);
		this.nick = str[7];
		this.type = HorseType.fromValue(str[8]);
	}
}
