//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.15 at 09:23:47 오후 KST 
//


package member;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for horseTypeKor.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="horseTypeKor">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="아메리칸쿼터호스"/>
 *     &lt;enumeration value="아메리칸새들호스"/>
 *     &lt;enumeration value="앵글로아랍"/>
 *     &lt;enumeration value="아팔루사"/>
 *     &lt;enumeration value="아라비안"/>
 *     &lt;enumeration value="아시안"/>
 *     &lt;enumeration value="클리블랜드베이"/>
 *     &lt;enumeration value="잉글리시해크니"/>
 *     &lt;enumeration value="저먼홀슈타인"/>
 *     &lt;enumeration value="하노베리안"/>
 *     &lt;enumeration value="리피차너"/>
 *     &lt;enumeration value="미주리폭스트로팅호스"/>
 *     &lt;enumeration value="모건"/>
 *     &lt;enumeration value="노리커"/>
 *     &lt;enumeration value="페르슈롱"/>
 *     &lt;enumeration value="샤이어"/>
 *     &lt;enumeration value="스탠더드브레드"/>
 *     &lt;enumeration value="서퍽"/>
 *     &lt;enumeration value="테네시워킹호스"/>
 *     &lt;enumeration value="서러브레드"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "horseTypeKor")
@XmlEnum
public enum HorseTypeKor {

    아메리칸쿼터호스,
    아메리칸새들호스,
    앵글로아랍,
    아팔루사,
    아라비안,
    아시안,
    클리블랜드베이,
    잉글리시해크니,
    저먼홀슈타인,
    하노베리안,
    리피차너,
    미주리폭스트로팅호스,
    모건,
    노리커,
    페르슈롱,
    샤이어,
    스탠더드브레드,
    서퍽,
    테네시워킹호스,
    서러브레드;

    public String value() {
        return name();
    }

    public static HorseTypeKor fromValue(String v) {
        return valueOf(v);
    }

}
