//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.15 at 07:35:38 오후 KST 
//


package member;

import java.awt.Image;
import java.awt.Canvas;
import java.io.*;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.net.URI;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for member complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="member">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="weight" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="picURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "member", propOrder = {
    "name",
    "age",
    "gender",
    "height",
    "weight",
    "picURL"
})
@XmlSeeAlso({
    Horse.class,
    Player.class
})
public class Member implements IMember, Cloneable, Serializable{

    @XmlElement(required = true)
    protected String name;
    @XmlElement(defaultValue = "0")
    protected int age;
    @XmlElement(defaultValue = "1")
    protected boolean gender;
    @XmlElement(defaultValue = "0.0")
    protected double height;
    @XmlElement(defaultValue = "0.0")
    protected double weight;
    @XmlElement(required = true)
    protected String picURL;
    @XmlAttribute(required = true)
    protected String id;
    //protected Image picture;
    
    public Member(){}
    public Member(String id, String name, int age, boolean gender, double height, double weight, String picURL){
		this.id = id;
		this.name = name;
		this.age = age;
		this.gender = gender;
		this.height = height;
		this.weight = weight;
		if(picURL.contains("://")) this.picURL = picURL;
		else this.picURL = "file:///" + picURL;
	}
    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the age property.
     * 
     */
    public int getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     */
    public void setAge(int value) {
        this.age = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     */
    public boolean isGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     */
    public void setGender(boolean value) {
        this.gender = value;
    }

    /**
     * Gets the value of the height property.
     * 
     */
    public double getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     */
    public void setHeight(double value) {
        this.height = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     */
    public double getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     */
    public void setWeight(double value) {
        this.weight = value;
    }

    /**
     * Gets the value of the picURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPicURL() {
        return picURL;
    }

    /**
     * Sets the value of the picURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPicURL(String value) {
        this.picURL = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }
    public String[] toStrings(){
		String[] str = new String[7];
		str[0] = this.id;
		str[1] = this.name;
		str[2] = this.age + "";
		str[3] = (this.gender)? "남" : "여";
		str[4] = this.height + "";
		str[5] = this.weight + "";
		str[6] = this.picURL;

		return str;
	}
    public void setData(String... str){
    	this.id = str[0];
    	this.name = str[1];
    	this.age = Integer.parseInt(str[2]);
    	this.gender = (str[3].equals("남"))? true : false;
    	this.height = Double.parseDouble(str[4]);
    	this.weight = Double.parseDouble(str[5]);
    	this.picURL = str[6];
    }
    public Object[] toArray(){
    	Object[] obj = new Object[7];
    	obj[0] = this.id;
    	obj[1] = this.name;
    	obj[2] = new Integer(this.age);
    	obj[3] = new Boolean(this.gender);
    	obj[4] = new Double(this.height);
    	obj[5] = new Double(this.weight);
		obj[6] = this.getPicURL();
		return obj;
    }
    public String[] getColumnName(){
		String[] str = {"ID", "이름", "나이", "성별", "신장(m)", "몸무게(kg)", "사진"};
		return str;
	}
    
    public IMember clone(){
    	try {
			return (IMember)super.clone();
		} catch (CloneNotSupportedException e) {
			return null;
		}
    }
}
